name: 👮

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Build
        run: make pyz

      - name: Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: 'automated release at commit ${{ github.sha }}'
          draft: false
          prerelease: false

      - name: Release
        uses: csexton/release-asset-action@v2
        with:
          file: app.pyz
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
